# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
sass_dir: _sass

# Build settings
markdown: kramdown
#kramdown:
#  auto_ids:  false

### site serving configuration ###
exclude: [CNAME, README.txt, LICENSE.txt, .gitignore]
permalink: / ## disables post output
timezone: null
highlighter: rouge

name: Ultisquash
description: 3-on-3 ultimate on a squash court
description_encoded: 3-on-3+ultimate+on+a+squash+court
url: http://ultisquash.com
url_encoded: http%3A%2F%2Fultisquash.com
